### ISSUE TITLE
PROJECT SPACE - MVP Checklist

### ISSUE THREAD

**Issue by dlq** [neurohub/neurohub_asana#54]
Adding links to specific features issues

- [x] ORCID account - https://github.com/neurohub/neurohub-asana/issues/102
- [ ] Multiple projects per user - https://github.com/neurohub/neurohub-asana/issues/103
- [x] Add collaborators - https://github.com/neurohub/neurohub-asana/issues/104
- [x] Collaborator view only permission - https://github.com/neurohub/neurohub-asana/issues/105
- [x] Collaborator edit permission - https://github.com/neurohub/neurohub-asana/issues/106
- [x] Upload files - https://github.com/neurohub/neurohub-asana/issues/107
- [ ] Project content via API - https://github.com/neurohub/neurohub-asana/issues/74
- [ ] Search - https://github.com/neurohub/neurohub-asana/issues/108
---
Bonus
- [ ] Public project - https://github.com/neurohub/neurohub-asana/issues/109
